version: "3"

networks:
  mischaBackend:
    name: mischa_backend

services:
  frontendMischa:
    mem_limit: 128m
    cpus: 0.1

    restart: unless-stopped
    image: mimasala/uek223-extended_frontend:latest
    container_name: frontendMischa
    depends_on:
      - backendMischa
    ports:
      - "8010:80"
  backendMischa:
    mem_limit: 128m
    cpus: 0.1

    restart: unless-stopped
    image: mimasala/uek223-extended_backend:latest
    ports:
      - "8095:8080"

  redisMischa:
    image: redis
    restart: unless-stopped
    ports:
      - "6379"

  postgresMischa:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432'
    volumes:
      - db-postgres-mischa:/var/lib/postgresql/data
  gorseMischa:
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - "8086"   # gRPC port
      - "8088"   # HTTP port
    environment:
      # Use Redis as cache storage backend.
      GORSE_CACHE_STORE: redis://redisMischa:6379
      # Use MySQL as data storage backend.
      GORSE_DATA_STORE: postgres://postgres:postgres@postgresMischa:5432/postgres?sslmode=disable
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      # Mount the configuration file.
      - ./config.toml:/etc/gorse/config.toml
    depends_on:
      - redisMischa
      - postgresMischa

volumes:
    db-postgres-mischa:
      driver: local