name: deploy hello test hahahahahahahhahah
on:
  push:
    branches: [master]
jobs:
  deploy:
    say-hello:
      runs-on: ubuntu-latest
      steps:
        name: say hello
        run: echo "hello world"
